name: Black

on:
  pull_request:
    branches:
    - master

jobs:
  format_with_black:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install black
      run: |
        pip install black
    - name: Format with black
      run: |
        python -m black --check -l 100 -t py36 finn/
