name: Pytest

on:
  pull_request:
    branches:
    - master

jobs:
  test_with_pytest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install package
      run: |
        pip install -e .
        pip install pytest
    - name: Test with Pytest
      run: |
        python -m pytest -vv tests
